---

- name: Install dependencies
  become: true
  apt: name={{ item }} update_cache=yes
  with_items:
    - git
    - python-dev
    - python-virtualenv

- name: Install via PIP and virtualenv
  become: false
  pip: |
    chdir={{ bot_services_path }}
    virtualenv={{ bot_services_path }}/.venv
    virtualenv_command={{ virtualenv_path }}
    requirements=requirements.txt
